# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_repo_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='file_repo_service.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x66ile_repo_service.proto\".\n\x08\x46ileInfo\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x14\n\x0c\x64ownload_url\x18\x02 \x02(\t\"\x14\n\x06\x46ileId\x12\n\n\x02id\x18\x01 \x02(\x03\x32W\n\x0f\x46ileRepoService\x12 \n\nUploadFile\x12\t.FileInfo\x1a\x07.FileId\x12\"\n\x0c\x44ownloadFile\x12\x07.FileId\x1a\t.FileInfo'
)




_FILEINFO = _descriptor.Descriptor(
  name='FileInfo',
  full_name='FileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FileInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='download_url', full_name='FileInfo.download_url', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=73,
)


_FILEID = _descriptor.Descriptor(
  name='FileId',
  full_name='FileId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='FileId.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['FileInfo'] = _FILEINFO
DESCRIPTOR.message_types_by_name['FileId'] = _FILEID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileInfo = _reflection.GeneratedProtocolMessageType('FileInfo', (_message.Message,), {
  'DESCRIPTOR' : _FILEINFO,
  '__module__' : 'file_repo_service_pb2'
  # @@protoc_insertion_point(class_scope:FileInfo)
  })
_sym_db.RegisterMessage(FileInfo)

FileId = _reflection.GeneratedProtocolMessageType('FileId', (_message.Message,), {
  'DESCRIPTOR' : _FILEID,
  '__module__' : 'file_repo_service_pb2'
  # @@protoc_insertion_point(class_scope:FileId)
  })
_sym_db.RegisterMessage(FileId)



_FILEREPOSERVICE = _descriptor.ServiceDescriptor(
  name='FileRepoService',
  full_name='FileRepoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=97,
  serialized_end=184,
  methods=[
  _descriptor.MethodDescriptor(
    name='UploadFile',
    full_name='FileRepoService.UploadFile',
    index=0,
    containing_service=None,
    input_type=_FILEINFO,
    output_type=_FILEID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DownloadFile',
    full_name='FileRepoService.DownloadFile',
    index=1,
    containing_service=None,
    input_type=_FILEID,
    output_type=_FILEINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILEREPOSERVICE)

DESCRIPTOR.services_by_name['FileRepoService'] = _FILEREPOSERVICE

# @@protoc_insertion_point(module_scope)
