# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: localized_string.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='localized_string.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16localized_string.proto\"\"\n\rStringRequest\x12\x11\n\tstring_id\x18\x01 \x02(\x03\" \n\x0fLocalizedString\x12\r\n\x05value\x18\x01 \x02(\t2D\n\x13LocalizationHandler\x12-\n\tgetString\x12\x0e.StringRequest\x1a\x10.LocalizedString'
)




_STRINGREQUEST = _descriptor.Descriptor(
  name='StringRequest',
  full_name='StringRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_id', full_name='StringRequest.string_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=60,
)


_LOCALIZEDSTRING = _descriptor.Descriptor(
  name='LocalizedString',
  full_name='LocalizedString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='LocalizedString.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['StringRequest'] = _STRINGREQUEST
DESCRIPTOR.message_types_by_name['LocalizedString'] = _LOCALIZEDSTRING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StringRequest = _reflection.GeneratedProtocolMessageType('StringRequest', (_message.Message,), {
  'DESCRIPTOR' : _STRINGREQUEST,
  '__module__' : 'localized_string_pb2'
  # @@protoc_insertion_point(class_scope:StringRequest)
  })
_sym_db.RegisterMessage(StringRequest)

LocalizedString = _reflection.GeneratedProtocolMessageType('LocalizedString', (_message.Message,), {
  'DESCRIPTOR' : _LOCALIZEDSTRING,
  '__module__' : 'localized_string_pb2'
  # @@protoc_insertion_point(class_scope:LocalizedString)
  })
_sym_db.RegisterMessage(LocalizedString)



_LOCALIZATIONHANDLER = _descriptor.ServiceDescriptor(
  name='LocalizationHandler',
  full_name='LocalizationHandler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=96,
  serialized_end=164,
  methods=[
  _descriptor.MethodDescriptor(
    name='getString',
    full_name='LocalizationHandler.getString',
    index=0,
    containing_service=None,
    input_type=_STRINGREQUEST,
    output_type=_LOCALIZEDSTRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCALIZATIONHANDLER)

DESCRIPTOR.services_by_name['LocalizationHandler'] = _LOCALIZATIONHANDLER

# @@protoc_insertion_point(module_scope)
