# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import user_message_pb2 as user__message__pb2


class UserMessageHandlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleMessage = channel.unary_stream(
                '/UserMessageHandler/HandleMessage',
                request_serializer=user__message__pb2.UserMessage.SerializeToString,
                response_deserializer=user__message__pb2.ServerResponse.FromString,
                )


class UserMessageHandlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HandleMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserMessageHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.HandleMessage,
                    request_deserializer=user__message__pb2.UserMessage.FromString,
                    response_serializer=user__message__pb2.ServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserMessageHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserMessageHandler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HandleMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/UserMessageHandler/HandleMessage',
            user__message__pb2.UserMessage.SerializeToString,
            user__message__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
