# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backend_service.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x62\x61\x63kend_service.proto\"\x1c\n\x0eSimpleResponse\x12\n\n\x02ok\x18\x01 \x02(\x08\"\x16\n\x08\x45ntityId\x12\n\n\x02id\x18\x01 \x02(\x03\",\n\rCreateTeamMsg\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05owner\x18\x02 \x02(\x03\"%\n\tNamedInfo\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x0c\n\x04name\x18\x02 \x02(\t\"T\n\x0bMeetingInfo\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x0f\n\x07\x63reator\x18\x02 \x02(\x03\x12\x0c\n\x04team\x18\x03 \x02(\x03\x12\x0c\n\x04\x64\x65sc\x18\x04 \x02(\t\x12\x0c\n\x04time\x18\x05 \x02(\x03\"0\n\rParticipating\x12\x0e\n\x06object\x18\x01 \x02(\x03\x12\x0f\n\x07subject\x18\x02 \x02(\x03\x32\xa4\x03\n\x0e\x42\x61\x63kendService\x12\'\n\nCreateTeam\x12\x0e.CreateTeamMsg\x1a\t.EntityId\x12(\n\rGetOwnedTeams\x12\t.EntityId\x1a\n.NamedInfo0\x01\x12$\n\x0bGetTeamInfo\x12\t.EntityId\x1a\n.NamedInfo\x12\x30\n\rAddTeamMember\x12\x0e.Participating\x1a\x0f.SimpleResponse\x12(\n\rCreateMeeting\x12\x0c.MeetingInfo\x1a\t.EntityId\x12\x32\n\x11UpdateMeetingInfo\x12\x0c.MeetingInfo\x1a\x0f.SimpleResponse\x12+\n\x10GetOwnedMeetings\x12\t.EntityId\x1a\n.NamedInfo0\x01\x12\x31\n\x0e\x41\x64\x64Participant\x12\x0e.Participating\x1a\x0f.SimpleResponse\x12)\n\x0eGetMeetingInfo\x12\t.EntityId\x1a\x0c.MeetingInfo'
)




_SIMPLERESPONSE = _descriptor.Descriptor(
  name='SimpleResponse',
  full_name='SimpleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='SimpleResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=53,
)


_ENTITYID = _descriptor.Descriptor(
  name='EntityId',
  full_name='EntityId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='EntityId.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=77,
)


_CREATETEAMMSG = _descriptor.Descriptor(
  name='CreateTeamMsg',
  full_name='CreateTeamMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CreateTeamMsg.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owner', full_name='CreateTeamMsg.owner', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=123,
)


_NAMEDINFO = _descriptor.Descriptor(
  name='NamedInfo',
  full_name='NamedInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='NamedInfo.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='NamedInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=162,
)


_MEETINGINFO = _descriptor.Descriptor(
  name='MeetingInfo',
  full_name='MeetingInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MeetingInfo.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creator', full_name='MeetingInfo.creator', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='team', full_name='MeetingInfo.team', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desc', full_name='MeetingInfo.desc', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='MeetingInfo.time', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=248,
)


_PARTICIPATING = _descriptor.Descriptor(
  name='Participating',
  full_name='Participating',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='object', full_name='Participating.object', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject', full_name='Participating.subject', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=298,
)

DESCRIPTOR.message_types_by_name['SimpleResponse'] = _SIMPLERESPONSE
DESCRIPTOR.message_types_by_name['EntityId'] = _ENTITYID
DESCRIPTOR.message_types_by_name['CreateTeamMsg'] = _CREATETEAMMSG
DESCRIPTOR.message_types_by_name['NamedInfo'] = _NAMEDINFO
DESCRIPTOR.message_types_by_name['MeetingInfo'] = _MEETINGINFO
DESCRIPTOR.message_types_by_name['Participating'] = _PARTICIPATING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleResponse = _reflection.GeneratedProtocolMessageType('SimpleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLERESPONSE,
  '__module__' : 'backend_service_pb2'
  # @@protoc_insertion_point(class_scope:SimpleResponse)
  })
_sym_db.RegisterMessage(SimpleResponse)

EntityId = _reflection.GeneratedProtocolMessageType('EntityId', (_message.Message,), {
  'DESCRIPTOR' : _ENTITYID,
  '__module__' : 'backend_service_pb2'
  # @@protoc_insertion_point(class_scope:EntityId)
  })
_sym_db.RegisterMessage(EntityId)

CreateTeamMsg = _reflection.GeneratedProtocolMessageType('CreateTeamMsg', (_message.Message,), {
  'DESCRIPTOR' : _CREATETEAMMSG,
  '__module__' : 'backend_service_pb2'
  # @@protoc_insertion_point(class_scope:CreateTeamMsg)
  })
_sym_db.RegisterMessage(CreateTeamMsg)

NamedInfo = _reflection.GeneratedProtocolMessageType('NamedInfo', (_message.Message,), {
  'DESCRIPTOR' : _NAMEDINFO,
  '__module__' : 'backend_service_pb2'
  # @@protoc_insertion_point(class_scope:NamedInfo)
  })
_sym_db.RegisterMessage(NamedInfo)

MeetingInfo = _reflection.GeneratedProtocolMessageType('MeetingInfo', (_message.Message,), {
  'DESCRIPTOR' : _MEETINGINFO,
  '__module__' : 'backend_service_pb2'
  # @@protoc_insertion_point(class_scope:MeetingInfo)
  })
_sym_db.RegisterMessage(MeetingInfo)

Participating = _reflection.GeneratedProtocolMessageType('Participating', (_message.Message,), {
  'DESCRIPTOR' : _PARTICIPATING,
  '__module__' : 'backend_service_pb2'
  # @@protoc_insertion_point(class_scope:Participating)
  })
_sym_db.RegisterMessage(Participating)



_BACKENDSERVICE = _descriptor.ServiceDescriptor(
  name='BackendService',
  full_name='BackendService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=301,
  serialized_end=721,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTeam',
    full_name='BackendService.CreateTeam',
    index=0,
    containing_service=None,
    input_type=_CREATETEAMMSG,
    output_type=_ENTITYID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOwnedTeams',
    full_name='BackendService.GetOwnedTeams',
    index=1,
    containing_service=None,
    input_type=_ENTITYID,
    output_type=_NAMEDINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTeamInfo',
    full_name='BackendService.GetTeamInfo',
    index=2,
    containing_service=None,
    input_type=_ENTITYID,
    output_type=_NAMEDINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddTeamMember',
    full_name='BackendService.AddTeamMember',
    index=3,
    containing_service=None,
    input_type=_PARTICIPATING,
    output_type=_SIMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateMeeting',
    full_name='BackendService.CreateMeeting',
    index=4,
    containing_service=None,
    input_type=_MEETINGINFO,
    output_type=_ENTITYID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateMeetingInfo',
    full_name='BackendService.UpdateMeetingInfo',
    index=5,
    containing_service=None,
    input_type=_MEETINGINFO,
    output_type=_SIMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOwnedMeetings',
    full_name='BackendService.GetOwnedMeetings',
    index=6,
    containing_service=None,
    input_type=_ENTITYID,
    output_type=_NAMEDINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddParticipant',
    full_name='BackendService.AddParticipant',
    index=7,
    containing_service=None,
    input_type=_PARTICIPATING,
    output_type=_SIMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMeetingInfo',
    full_name='BackendService.GetMeetingInfo',
    index=8,
    containing_service=None,
    input_type=_ENTITYID,
    output_type=_MEETINGINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BACKENDSERVICE)

DESCRIPTOR.services_by_name['BackendService'] = _BACKENDSERVICE

# @@protoc_insertion_point(module_scope)
