name: on-push-integration-tests-workflow
on: push
jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Compile protobufs
        run: sh protobufs/compile.sh
      - name: Build test env
        run: docker compose -f test-docker-compose.yml up -d
    
  test:
    runs-on: self-hosted
    needs: [setup]
    steps:
      - name: Test
        run: docker compose -f test-docker-compose.yml run --no-TTY integration-tests-adapter pytest -v
  
  cleanup:
    runs-on: self-hosted
    needs: [test]
    if: always()
    steps:
      - name: Shutdown
        run: docker compose -f test-docker-compose.yml down
      - name: Cleanup
        run: docker image prune -a -f
  
