name: on-push-integration-tests-workflow
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Compile protobufs
        run: sh protobufs/compile.sh
      - name: Build test env
        run: docker compose -f test-docker-compose.yml up -d
      - name: Test
        run: docker compose -f test-docker-compose.yml run integration-tests-adapter pytest -v
      - name: Shutdown
        run: docker compose -f test-docker-compose.yml down
